# .github/workflows/npm-publish-notification.yml
name: NPM Publish Notification

on:
  release:
    types: [published]
  # Or trigger on npm publish
  push:
    tags:
      - 'v*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get package info
        id: package
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          echo "NAME=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
      
      - name: Send Google Chat notification
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          -d '{
            "text": "🚀 *${{ steps.package.outputs.NAME }}* v${{ steps.package.outputs.VERSION }} has been published to npm!\n\nView on npm: https://www.npmjs.com/package/${{ steps.package.outputs.NAME }}\nGitHub Release: ${{ github.event.release.html_url }}"
          }' \
          ${{ secrets.GOOGLE_CHAT_WEBHOOK }}